- name: add  samba user
  hosts: "{{ hosts_prompt }}"
  vars_prompt:
    - name: "username"
      prompt: "Username? [user1]"
      private: no
    - name: "password"
      prompt: "Password? [secret]"
      private: yes

  tasks:

  - name: add user {{user}}
    shell: "useradd -s /bin/false {{username}}"
    become: yes
    
  - name: set password (smbpasswd) for {{username}}
    shell: "(echo ""{{password}}""; echo ""{{password}}"") | smbpasswd -s -a {{user}}"
    become: yes
