- name: generate ssh key and install foreign ssh keys
  hosts: "{{ hosts_prompt }}"

  tasks:

   - name: "Run ssh commands to create new ssh keys"
     shell: ssh-keygen -f ~/.ssh/id_rsa -t ecdsa -b 512 -q -N ''
     args:
      creates: ~/.ssh/id_ecdsa

   - name: Set authorized key from file
     authorized_key:
      user: pi
      state: present
      key: "{{ lookup('file', '/home/pi/.ssh/id_ecdsa.pub') }}"
