- name: install docker via webscript and docker-compose via pip
  hosts: "{{ hosts_prompt }}"
  gather_facts: no

  tasks:

  # Example that prints return information from the previous task
  - name: is docker installed?
    shell: docker --version
    register: docker_installed
    ignore_errors: yes
    # no_log: True

  - name: if docker is already installed skip related tasks
    debug:
      var: docker_installed.stdout
    when: docker_installed is succeeded

  - include: tasks/task-inst-upd-pip.yml

  - name: run script from get.docker.com
    shell: "curl -fsSL get.docker.com -o- | sudo -E bash"
    become: yes
    when: docker_installed is failed

  - name: add {{ ansible_user }} to docker group
    user:
      name: '{{ ansible_user }}'
      groups: docker
    become: yes
    when: docker_installed is failed

  # Install (docker-compose) python package.
  - name: Install docker-compose python package
    ansible.builtin.pip:
      name: docker-compose
