- name: install certbot an acquire certificate from letsencrypt
  hosts: "{{ hosts_prompt }}"
  vars_prompt:
    - name: "domain"
      prompt: "What is the domain name? [something.com]"
      private: no
      when: domain is not defined
    - name: "email"
      prompt: "What is the email address? [user@mail.com]"
      private: no
      when: email is not defined

  tasks:

  - include: tasks/task-rpi-inst-certbot.yml
    when: (ansible_lsb['id'] == "Raspbian") and
          (ansible_lsb['major_release'] == "9")

  - include: tasks/task-ubu-inst-certbot.yml
    when: (ansible_lsb['id'] == "Ubuntu") and
          (ansible_lsb['release'] == "18.04" or ansible_lsb['release'] == "16.04")
