- name: generate ssh key and install foreign ssh keys
  hosts: "{{ hosts_prompt }}"
  gather_facts: no

  tasks:

   - name: "Run ssh commands to create new ssh keys"
     shell: ssh-keygen -f ~/.ssh/id_ecdsa -t ecdsa -b 521 -q -N ''
     args:
      creates: ~/.ssh/id_ecdsa

   - name: Set authorized key from github user
     shell: wget -O - https://github.com/"{{ user_prompt }}".keys > /home/pi/.ssh/authorized_keys
     args:
      creates: ~/.ssh/authorized_keys
      
