#run with: ansible-playbook inst-testing-repository.yml -e "hosts_prompt=<client>"
#add testing repository to raspbian an set stable repository as default
#afterwards run "sudo apt-get install xyz -t testing" will install the version from the testing repository
#"apt-cache showpkg xyz" will show the versions and detailed informations from both repositories

- name: setup testing repository for raspbian
  hosts: "{{ hosts_prompt }}"
  
  tasks:

- include: tasks/task-testing-repository.yml
