- name: install docker via webscript and docker-compose via pip
  hosts: "{{ hosts_prompt }}"

  tasks:

  - include: tasks/task-inst-upd-pip.yml

  - name: run script from get.docker.com
    shell: "curl -fsSL get.docker.com -o- | sudo -E bash"
    become: yes

  - name: add pi to docker group
    user:
      name: '{{ username | default(pi) }}'
      groups: docker
    become: yes

  # Install (docker-compose) python package.
  - pip:
     name: docker-compose
