#run with: ansible-playbook inst-testing-repository.yml -e "hosts_prompt=<client>"
#add testing repository to raspbian an set stable repository as default
#afterwards run "sudo apt-get install xyz -t testing" will install the version from the testing repository
#"apt-cache showpkg xyz" will show the versions and detailed informations from both repositories

- name: setup testing repository for raspbian
  hosts: "{{ hosts_prompt }}"
  
  tasks:

  - name: create testing.list in /etc/apt/sources.list.d/
    lineinfile:
     dest: /etc/apt/sources.list.d/testing.list
     line: 'deb http://raspbian.raspberrypi.org/raspbian/ testing main contrib non-free rpi'
     state: present
     owner: root
     group: root
     mode: "0644"
     create: yes
    become: yes

  - name: create testing.pref in /etc/apt/preferences.d/
    lineinfile:
     dest: /etc/apt/preferences.d/testing.pref
     line: "{{item}}"
     state: present
     owner: root
     group: root
     mode: "0644"
     create: yes
    with_items:
     - "Package: *"
     - "Pin: release a=testing"
     - "Pin-Priority: 750"
    become: yes

  - name: create stable.pref in /etc/apt/preferences.d/
    lineinfile:
     dest: /etc/apt/preferences.d/stable.pref
     line: "{{item}}"
     state: present
     owner: root
     group: root
     mode: "0644"
     create: yes
    with_items:
     - "Package: *"
     - "Pin: release a=stable"
     - "Pin-Priority: 900"
    become: yes
