- name: install docker via webscript and docker-compose via pip
  hosts: "{{ hosts_prompt }}"

  tasks:

  - name: run script from get.docker.com
    shell: "curl -fsSL get.docker.com -o- | sudo -E bash"
    become: yes

  - name: Install "pip" package if missing
    apt:
     update_cache: yes
     cache_valid_time: 3600
     name: "{{ item }}"
     state: present
    become: yes
    with_items:
       - pip

  - name: add pi to docker group
    user:
      name: pi
      groups: docker
    become: yes

  # Install (docker-compose) python package.
  - pip:
    name: docker-compose
