 - name: Install "python-pip" package if missing
   apt:
    update_cache: yes
    cache_valid_time: 3600
    name: python3-pip
    state: present
   become: yes

 - name: Update pip to the newest version via pip
   pip:
    name: pip
    executable: pip3
    state: latest
    # might fail due to executable path on first run?